export const popupStyle = {
  modalContainer: {
    position: "absolute",
    top: "20%",
    left: "37%",
    width: 500,
    height: "600px",
    p: 5,
    backgroundColor: "white",
    borderRadius: "20px",
  },
  stackHeader: {
    backgroundColor: "#daebf8",
    m: "10px",
    height: "90px",
    borderRadius: "5px",
    textAlign: "center",
    pt: "20px",
  },
  goodToPassUp: {
    fontSize: "12px",
    letterSpacing: "2px",
    fontWeight: "bold",
  },
  orderEuroStyle: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  euroFieldStyle: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    height: "22px",
    backgroundColor: "white",
    borderRadius: "5px",
    margin: "4px",
    padding: "4px",
  },
  infoIconStyle: {
    width: "15px",
    height: "15px",
    ml: "5px",
    boxSizing: "content-box",
    pt: "5px",
  },
  infoFooterContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  cartItemsStackStyle: {
    borderTop: "1px solid rgba(224, 221, 222, 0.4)",
    mt: "20px",
    mb: "20px",
    borderBottom: "1px solid rgba(224, 221, 222, 0.4)",
  },
};
