export const popupStyle = {
  modalContainer: {
    position: "absolute",
    top: "20%",
    left: "37%",
    width: 500,
    height: "600px",
    p: 5,
    backgroundColor: "white",
    borderRadius: "20px",
  },
  stackHeader: {
    backgroundColor: "#daebf8",
    m: "10px",
    height: "90px",
    borderRadius: "5px",
    textAlign: "center",
    pt: "20px",
  },
  goodToPassUp: {
    fontSize: "12px",
    letterSpacing: "2px",
    fontWeight: "bold",
  },
  orderEuroStyle: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  euroFieldStyle: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    height: "22px",
    backgroundColor: "white",
    borderRadius: "5px",
    margin: "4px",
    padding: "4px",
  },
  infoIconStyle: {
    width: "15px",
    height: "15px",
    ml: "5px",
    boxSizing: "content-box",
    pt: "5px",
  },
  infoFooterContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    mb: "20px",
  },
  cartItemsStackStyle: {
    borderTop: "1px solid rgba(224, 221, 222, 0.4)",
    mt: "20px",
    mb: "20px",
    borderBottom: "1px solid rgba(224, 221, 222, 0.4)",
  },
  itemCartContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    height: "100px",
    alignItems: "flex-start",
    pt: "15px",
    pb: "15px",
  },
  itemInfoContainer: {
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    m: "0 20px",
    alignItems: "flex-start",
    justifyContent: "center",
    width: "250px",
  },
  countContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    mt: "5px",
    p: "4px",
    width: "70px",
    height: "25px",
    border: "2px solid black",
    borderRadius: "4px",
  },
  priceContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "flex-end",
    mt: "30px",
    ml: "5px",
  },
};
